version: "3"
services:
  db:
    container_name: 'db'
    image: 'postgres'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'devops2'

    volumes:
      - bank-data:/var/lib/postgresql/data
    networks:
      - 'mynet'

  app:
    container_name: 'banking_app'
    image: 'kermtuncr19/banking_management'
    build: .
    restart: 'on-failure'
    ports:
      - '9090:9090'
    environment:
      DB_HOST: 'db'
      DB_USER: 'postgres'
      DB_PASSWORD: '1234'
      DB_PORT: '5432'
      DB_NAME: 'devops2'
    networks:
      - 'mynet'
    depends_on:
      - 'db'
networks:
  mynet:
    external: true
volumes:
  bank-data:
